baseURL = 'https://blakejc94.github.io/'
languageCode = 'en-us'
title = 'Blog'
theme = "m10c"
sectionPagesMenu = 'main'


[params]
  author = "Blake Cook"
  description = "Dimensions are a social construct."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/BlakeJC94"
