baseURL = 'https://blakejc94.github.io/'
languageCode = 'en-us'
title = 'Blog // BlakeJC94'
theme = "m10c"
sectionPagesMenu = 'main'

[menus]
[[menus.main]]
    identifier = "home"
    name = 'Home'
    url = "/"
    pageRef = '/'
    weight = 10


[params]
  author = "Blake Cook"
  description = "Dimensions are a social construct."
  favicon = "./favicon.ico"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/BlakeJC94"

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "www.linkedin.com/in/blake-cook-a476432b3"
