baseURL = 'https://blakejc94.github.io/'
languageCode = 'en-us'
title = 'Blog'
theme = "m10c"
sectionPagesMenu = 'main'

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
[[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 30


[params]
  author = "Blake Cook"
  description = "Dimensions are a social construct."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/BlakeJC94"

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "www.linkedin.com/in/blake-cook-a476432b3"
